### ISSUE TITLE
Some questions about the arm64 modifications

### ISSUE THREAD

**Issue by zhuowei** [fergofrog/xnu#1]
Thanks for your hard work in getting xnu to compile. I have a few questions:

- Why specifically define `-DARM64_BOARD_CONFIG_T8011`?

It might be better to use `-DARM64_BOARD_CONFIG_$(CURRENT_MACHINE_CONFIG)` instead and populate the `SUPPORTED_ARM64_MACHINE_CONFIGS`, so that one can specify the board to build from the make command by running `make TARGET_CONFIGS="DEBUG ARM64 T8011"`.

- Where is the "correct" place to define CONFIG_EMBEDDED anyways? Should it go in `config/MASTER` instead?

`config/MASTER.arm64` specifies `config_embedded`, but there's no corresponding option in `config/MASTER`. I tried adding

`options                CONFIG_EMBEDDED                 # <config_embedded>`

and that did define CONFIG_EMBEDDED for arm64.

- I saw that you're one of the [two repositories](https://github.com/search?q=SUPPORTED_ARM64_MACHINE_CONFIGS&type=Code) on Github that's trying to build Apple's arm64 xnu. Have you considered helping out the [RaspberryPi-XNU](https://github.com/aBradleyUno/RaspberryPi-XNU) project?

**Comment by fergofrog** [comment]
Thanks for the great ideas @zhuowei. I've given an attempt at implementing the first two points in commit 2c9da458dce46fbf30cbea372bcaba5ea5578248. I really like the idea of using the `MACHINE_CONFIG` to specify the target board. Let me know what you think and I'll merge it in and update the blog post.

For the last point, for me this repo is so I could get a working `compile_commands.json` to work with Woboq, as well as be able to do some analysis with the AST. I'm not hoping to run it on a real device. Certainly trying to get all the MSR's and device trees set up is more work than I'm up for with my spare time.
